### ISSUE TITLE
Idea: store indexes only when they have many "1"s

### ISSUE THREAD

**Issue by staltz** [arj03/jitdb#5]
Hey @arj03 I've been thinking about how to use JITDB for `contact` messages (like we discussed in the cabin) and I've dropped the matrix idea (because it's not better than just a hash table of "from" and "to", like you do with `hops` in ssb-browser-core), but while whiteboarding I had another idea.

![wb](https://user-images.githubusercontent.com/90512/95103490-537c8100-073d-11eb-8dd5-b30c18210cde.jpg)

As far as I understood, for every query-driven-index in jitdb, we save a bit vector file. The downside of this is that we may end up with many bit vector files. What if we check the quantity of "1"s in the bit vector before saving, and if the total count is less than N, not save it in disk? 

For example, consider N=4 in the whiteboard example above, there are:

- 7 msgs `contact`
- 3 msgs `contact` AND mine
- 2 msgs `contact` AND mine AND `following===true`

The number `3` is small enough that we could "stop here", we don't need to create files for bit vector that is a strict subset of this. So we **would** store the second index with 3, but **not** store the third index with `2`. Maybe the logic is "when the index ones-count is less than N, this index is the last one to be stored in disk, any `AND`d subset indexes won't be stored".

The rationale being that it's fast enough to pull out 3 msgs and iterate through all of them and re-run the query logic in memory.

I have a couple other ideas, but I'll put them in different issues. I'm curious to hear your thoughts, and I'm not afraid if you tell me this idea is silly, I'm still just exploring this space.

**Comment by arj03** [comment]
> What if we check the quantity of "1"s in the bit vector before saving, and if the total count is less than N, not save it in disk?

I had that idea but discarded [it](https://github.com/arj03/jitdb/commit/70719ff5776f3563aa46bb680d37399c74403471), you can see the rationale there. I think the problem with many indexes would be better solved by lazy loading them when needed, this should cut down on initial load. 

> The rationale being that it's fast enough to pull out 3 msgs and iterate through all of them and re-run the query logic in memory.

The idea of saving how many results the index contains together with the index is a great idea! We already store the seq because we need to know when to update it, so it should be easy to add. Please note it is not count, its the size() function on the bitset. If you do a query on 3 parameters where you have an index of say the first, then you check how many results that have, and if its low enough you just filter directly instead of creating indexes for the other two as that is the slow part. What the threshold should be could probably be configured when loading jitdb, even better if it could be based on how many records can be read in 200ms or something like that.

The contact case is actually interested in that my gut reaction was to create the reduced index as I did in browser core, but I just tried changing the query in example to get contact messages from my profile instead of all and reduce that, which is 22ms. Granted this is a beefy laptop, but still, it might actually be fast enough to just to them on the fly.

**Comment by staltz** [comment]
> but I just tried changing the query in example to get contact messages from my profile instead of all and reduce that, which is 22ms. Granted this is a beefy laptop, but still, it might actually be fast enough to just to them on the fly.

Yes I think this should be acceptable, I would say that a non-beefy computer (mid-end smart phone) might take 80+ ms, and that's still fine. In practice, users don't open the profile screen of users that often, and they may open <20 profile screens during one session of using the app, so looking these things up on the fly should be fine.

As a general principle, as you said, loading the whole log and scanning it is not too slow (it's not too fast either, but not painfully slow), so loading a subset of the log and scanning it should be even less slow, so in general we should just make indexes for the purpose of decreasing the "scan size" until it's bearable.

> The idea of saving how many results the index contains together with the index is a great idea!
> If you do a query on 3 parameters where you have an index of say the first, then you check how many results that have, and if its low enough you just filter directly instead of creating indexes for the other two as that is the slow part.

Yes! I'm keen to try this out.

**Comment by staltz** [comment]
By the way, when mentioning absolute numbers (milliseconds etc), I think your beefy computer is a good reference, because on mobile it could get slower, but with a Rust implementation it could get faster, and in both of these cases I think it would be less than an order of magnitude.

E.g. maybe that query on mobile written in Rust would also be roughly 20ms.

**Comment by arj03** [comment]
Yes agree, I have jitdb running on my medium range phone in the form of browser demo. I also tested the jitdb stuff on my really old laptop which is comparable to a low end phone.

I looked at where contacts is used in browser and it doesn't need anything else then the graph per user once in a while so could def. use this direct query. Patchwork is a bit more involed, it seems to do a lot of filter based on blocked, but I think quite a lot of that code is there because we couldn't remove data for blocked feeds before. It was one of the things Bundy did and its supported by async-flumelog.

**Comment by arj03** [comment]
I booted my ancient laptop which is comparable to a low-end phone and the contacts query is 78ms :-)

**Comment by staltz** [comment]
I get happy when my estimates are accurate. 78ms is quite close to the >80ms estimate I made. :)

**Comment by arj03** [comment]
Indexes are now lazy loaded, this cuts down initial load from around 1400ms to 800ms.

**Comment by staltz** [comment]
Stale issue, created #8 instead.
